### ISSUE TITLE
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.

### ISSUE THREAD

**Issue by TryLittleHarder** [hello-maker/JTVAE_Python3#1]
Hi! I tried to run molvae/pretrain.py, but got this error `rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 4`.

**Comment by hello-maker** [comment]
Hi! 
I apologize for my late reply.
I think it would be better to use "JunctionTreeVAE" ( https://github.com/hello-maker/JunctionTreeVAE ) repository than to use "JTVAE_Python3"repository.
In the repository "JunctionTreeVAE", the problem you mentioned will be solved.\

Thank you!! :)
